name: tf-plan
on:
  pull_request:
    paths-ignore:
        - '**.md'
    branches:
        - dev
env:
    tf-wrkd: './terraform/main/'

jobs:
  plan:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "echo"
        run: |
         echo 'projects/${{vars.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/gh-oidc-terraform/providers/gh-oidc-terraform'
         echo 'gh-oidc-terraform@${{vars.GCP_PROJECT_ID}}.iam.gserviceaccount.com'

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/${{vars.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/gh-oidc-terraform/providers/gh-oidc-terraform'
          service_account: 'gh-oidc-terraform@${{vars.GCP_PROJECT_ID}}.iam.gserviceaccount.com'
     
      - name: Terraform Init
        shell: bash
        working-directory: ${{env.tf-wrkd}}
        run: terraform init -backend-config=../setup/terraform_backend/envs/${{vars.ENV}}/tf-backend.tfvars

      - name: Terraform Validate
        shell: bash
        working-directory: ${{env.tf-wrkd}}
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        shell: bash
        working-directory: ${{env.tf-wrkd}}
        run: |
            terraform plan -out="envs/${{vars.ENV}}/plan.tfplan" -detailed-exitcode 
            tf_exitcode=$?
            echo "exitcode=$tf_exitcode" >> $GITHUB_OUTPUT

    