name: tf-plan
on:
  pull_request:
    paths-ignore:
        - '**.md'
    branches-ignore:
        - dependabot/**

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write'
  pull-requests: 'write'

env:
  PROJECT_ID: ${{ secrets.DEV_PROJECT_ID }}
  TF_ENV: 'stage'
  TF_WORKING_DIR: 'terraform/setup'
  TF_VERSION: '~1.3.0'

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-oidc-terraform/providers/gh-oidc-terraform'
          service_account: 'gh-oidc-terraform@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
     
      - name: Terraform Init
        shell: bash
        working-directory: ${{env.tf-wrkd}}
        run: terraform init -backend-config=terraform_backend/${{vars.ENV}}/${{vars.ENV}}.tfbackend

      - name: Terraform Validate
        shell: bash
        working-directory: ${{env.tf-wrkd}}
        run: terraform validate -no-color


    